swagger: '2.0'
info:
  description: ''
  version: 1.0.0
  title: Notes backend
host: notestore.swagger.io
basePath: /v2
tags:
  - name: note
    description: Everything about your notes
schemes:
  - http
paths:
  /note:
    get:
      tags:
        - note
      summary: Get all notes
      description: ''
      operationId: getNotes
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/NotesReply'
    post:
      tags:
        - note
      summary: Add a new note
      description: ''
      operationId: addNote
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: note object that needs to be stored
          required: true
          schema:
            $ref: '#/definitions/Note'
      responses:
        '200':
          description: success
        '405':
          description: Validation exception
  '/note/{noteId}':
    get:
      tags:
        - note
      summary: Find note by ID
      description: Returns a single note
      operationId: getNoteById
      produces:
        - application/xml
        - application/json
      parameters:
        - name: noteId
          in: path
          description: ID of note to return
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: successful operation
          schema:
            $ref: '#/definitions/Note'
        '400':
          description: Invalid ID supplied
        '404':
          description: note not found
    delete:
      tags:
        - note
      summary: Deletes a note
      description: ''
      operationId: deleteNote
      produces:
        - application/xml
        - application/json
      parameters:
        - name: noteId
          in: path
          description: note id to delete
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: success
        '400':
          description: Invalid ID supplied
        '404':
          description: note not found
    put:
      tags:
        - note
      summary: Update an existing note
      description: ''
      operationId: updateNote
      consumes:
        - application/json
        - application/xml
      produces:
        - application/xml
        - application/json
      parameters:
        - in: body
          name: body
          description: note object that needs to be updated
          required: true
          schema:
            $ref: '#/definitions/Note'
      responses:
        '204':
          description: success
        '400':
          description: Invalid ID supplied
        '404':
          description: note not found
        '405':
          description: Validation exception
definitions:
  Note:
    type: object
    properties:
      id:
        type: integer
        format: int64
      title:
        type: string
      description:
        type: string
      category:
        type: string
        enum:
          - STUDY
          - WORK
          - PERSONAL
      priority:
        type: string
        enum:
          - LOW
          - NORMAL
          - HIGH
    xml:
      name: Note
  NotesReply:
    type: object
    properties:
      notes:
        type: array
        items:
          $ref: '#/definitions/Note'
